package wikicatalog

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
)

// TestHashContentMatchesGit locks the SHA-1 computation against
// outputs produced by real git hash-object. If this test ever drifts, git
// ingest would publish SHAs that disagree with what the legacy code returned
// via If-Match, silently breaking conditional requests from existing REST
// clients.
//
// The golden values were generated by:
//
//	printf 'hello\n'                     | git hash-object --stdin
//	printf ''                            | git hash-object --stdin
//	printf '# Home\n\nWelcome.\n'        | git hash-object --stdin
func TestHashContentMatchesGit(t *testing.T) {
	cases := []struct {
		name    string
		content []byte
		want    string
	}{
		{"hello", []byte("hello\n"), "ce013625030ba8dba906f756967f9e9ca394464a"},
		{"empty", []byte{}, "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391"},
		{"home", []byte("# Home\n\nWelcome.\n"), "eabec58e1c72d96c059124e2658698ba13727d57"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := HashContent(tc.content)
			if got != tc.want {
				t.Fatalf("HashContent = %q, want %q (git-hash-object output)",
					got, tc.want)
			}
		})
	}
}

func TestBlobStorePutGetHas(t *testing.T) {
	store := NewBlobStore(t.TempDir())
	ctx := context.Background()

	content := []byte("# Home\n\nWelcome.\n")
	sha, err := store.Put(ctx, content)
	if err != nil {
		t.Fatalf("Put: %v", err)
	}
	want := "eabec58e1c72d96c059124e2658698ba13727d57"
	if sha != want {
		t.Fatalf("Put returned sha %q, want %q", sha, want)
	}

	ok, err := store.Has(ctx, sha)
	if err != nil || !ok {
		t.Fatalf("Has(%q) = (%v, %v); want (true, nil)", sha, ok, err)
	}

	got, err := store.Get(ctx, sha)
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	if string(got) != string(content) {
		t.Fatalf("Get content mismatch")
	}
}

func TestBlobStorePutIsIdempotent(t *testing.T) {
	store := NewBlobStore(t.TempDir())
	ctx := context.Background()

	content := []byte("identical")
	sha1, err := store.Put(ctx, content)
	if err != nil {
		t.Fatalf("first Put: %v", err)
	}
	// Modify the on-disk file to detect any unwanted overwrite.
	abs, err := store.absPath(sha1)
	if err != nil {
		t.Fatalf("absPath: %v", err)
	}
	if err := os.WriteFile(abs, []byte("tampered"), 0o640); err != nil {
		t.Fatalf("tamper write: %v", err)
	}

	sha2, err := store.Put(ctx, content)
	if err != nil {
		t.Fatalf("second Put: %v", err)
	}
	if sha2 != sha1 {
		t.Fatalf("second Put returned different SHA: %q vs %q", sha2, sha1)
	}

	// On idempotent re-Put, existing content must be left as-is. This
	// is intentional: callers may use Put after restoring corrupted
	// data, in which case they should re-run integrity checks
	// themselves; the CAS contract is "content-addressed, immutable
	// once written."
	got, err := os.ReadFile(abs)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if string(got) != "tampered" {
		t.Fatalf("idempotent Put should not have rewritten file; got %q", got)
	}
}

func TestBlobStoreGetMissing(t *testing.T) {
	store := NewBlobStore(t.TempDir())
	_, err := store.Get(context.Background(),
		"0000000000000000000000000000000000000000")
	if !errors.Is(err, ErrBlobNotFound) {
		t.Fatalf("Get missing = %v, want ErrBlobNotFound", err)
	}
}

func TestBlobStoreDelete(t *testing.T) {
	store := NewBlobStore(t.TempDir())
	ctx := context.Background()

	sha, err := store.Put(ctx, []byte("body"))
	if err != nil {
		t.Fatalf("Put: %v", err)
	}
	if err := store.Delete(ctx, sha); err != nil {
		t.Fatalf("Delete: %v", err)
	}

	if ok, _ := store.Has(ctx, sha); ok {
		t.Fatal("Has returned true after Delete")
	}

	// Double-delete is a no-op for GC use cases.
	if err := store.Delete(ctx, sha); err != nil {
		t.Fatalf("second Delete: %v", err)
	}
}

func TestBlobStoreRejectsBadSHA(t *testing.T) {
	store := NewBlobStore(t.TempDir())
	ctx := context.Background()
	bad := []string{
		"",
		"short",
		strings.Repeat("g", 40),
		strings.Repeat("A", 40), // upper-case rejected; we store hex lower
		strings.Repeat("a", 41),
	}
	for _, s := range bad {
		t.Run(s, func(t *testing.T) {
			if _, err := store.Get(ctx, s); err == nil {
				t.Fatalf("Get(%q) expected error", s)
			}
			if _, err := store.Has(ctx, s); err == nil {
				t.Fatalf("Has(%q) expected error", s)
			}
			if err := store.Delete(ctx, s); err == nil {
				t.Fatalf("Delete(%q) expected error", s)
			}
		})
	}
}

// TestBlobStoreConcurrentPutSameContent confirms the "rename target
// already exists" race path returns success rather than surfacing the
// OS rename error. Without this branch, two parallel uploads of the
// same body would fail one of them.
func TestBlobStoreConcurrentPutSameContent(t *testing.T) {
	store := NewBlobStore(t.TempDir())
	ctx := context.Background()
	content := []byte("racey payload")
	const N = 32

	var wg sync.WaitGroup
	results := make(chan string, N)
	errs := make(chan error, N)
	wg.Add(N)
	for i := 0; i < N; i++ {
		go func() {
			defer wg.Done()
			sha, err := store.Put(ctx, content)
			if err != nil {
				errs <- err
				return
			}
			results <- sha
		}()
	}
	wg.Wait()
	close(errs)
	close(results)

	for err := range errs {
		t.Fatalf("concurrent Put error: %v", err)
	}
	var first string
	for sha := range results {
		if first == "" {
			first = sha
			continue
		}
		if sha != first {
			t.Fatalf("concurrent Puts returned different SHAs: %q vs %q",
				first, sha)
		}
	}
}

func TestBlobStorePathLayout(t *testing.T) {
	tmp := t.TempDir()
	store := NewBlobStore(tmp)
	_, err := store.Put(context.Background(), []byte("payload"))
	if err != nil {
		t.Fatalf("Put: %v", err)
	}
	sha := HashContent([]byte("payload"))
	want := filepath.Join(tmp, ".wikiblobs", sha[0:2], sha[2:4], sha)
	if _, err := os.Stat(want); err != nil {
		t.Fatalf("expected blob at %s: %v", want, err)
	}
}
